spring.application.name=compatibility-service
server.port=${SERVER_PORT}
catalog.url=${CATALOG_SERVICE_URL}

spring.datasource.url=jdbc:postgresql://${COMPATIBILITY_POSTGRES_HOST:postgres}:${COMPATIBILITY_POSTGRES_PORT:5432}/${COMPATIBILITY_POSTGRES_DB:hardtech_compatibility}
spring.datasource.username=${COMPATIBILITY_POSTGRES_USER}
spring.datasource.password=${COMPATIBILITY_POSTGRES_PASSWORD}
spring.datasource.hikari.connection-timeout=5000
